//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVA.DotNetReferenceImplementation
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509", ConfigurationName = "Nummervoorziening")]
    public interface INummervoorziening
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://xml.eld.nl/schemas/Nummervoorziening/201509/ping", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        pingResponse1 ping(pingRequest1 request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://xml.eld.nl/schemas/Nummervoorziening/201509/retrieveEckId", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        retrieveEckIdResponse1 retrieveEckId(retrieveEckIdRequest1 request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://xml.eld.nl/schemas/Nummervoorziening/201509/submitEckIdBatch", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        submitEckIdBatchResponse1 submitEckIdBatch(submitEckIdBatchRequest1 request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://xml.eld.nl/schemas/Nummervoorziening/201509/retrieveEckIdBatch", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        retrieveEckIdBatchResponse1 retrieveEckIdBatch(retrieveEckIdBatchRequest1 request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://xml.eld.nl/schemas/Nummervoorziening/201509/replaceEckId", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        replaceEckIdResponse1 replaceEckId(replaceEckIdRequest1 request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://xml.eld.nl/schemas/Nummervoorziening/201509/retrieveChains", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        retrieveChainsResponse retrieveChains(retrieveChainsRequest1 request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://xml.eld.nl/schemas/Nummervoorziening/201509/retrieveSectors", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        retrieveSectorsResponse retrieveSectors(retrieveSectorsRequest1 request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509")]
    public partial class PingRequest
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509")]
    public partial class Sector
    {

        private string idField;

        private string nameField;

        private string descriptionField;

        private ValidationStatus statusField;

        private System.DateTime lastEditedField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public ValidationStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public System.DateTime lastEdited
        {
            get
            {
                return this.lastEditedField;
            }
            set
            {
                this.lastEditedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509")]
    public enum ValidationStatus
    {

        /// <remarks/>
        Valid,

        /// <remarks/>
        NotValid,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509")]
    public partial class RetrieveSectorsRequest
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509")]
    public partial class Chain
    {

        private string idField;

        private string nameField;

        private string descriptionField;

        private ValidationStatus statusField;

        private System.DateTime lastEditedField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public ValidationStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public System.DateTime lastEdited
        {
            get
            {
                return this.lastEditedField;
            }
            set
            {
                this.lastEditedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509")]
    public partial class RetrieveChainsRequest
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509")]
    public partial class ReplaceEckIdResponse
    {

        private EckId eckIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public EckId eckId
        {
            get
            {
                return this.eckIdField;
            }
            set
            {
                this.eckIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509")]
    public partial class EckId
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509")]
    public partial class ReplaceEckIdRequest
    {

        private HPgn hpgnOldField;

        private HPgn hpgnNewField;

        private string chainIdField;

        private string sectorIdField;

        private System.DateTime effectiveDateField;

        private bool effectiveDateFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public HPgn hpgnOld
        {
            get
            {
                return this.hpgnOldField;
            }
            set
            {
                this.hpgnOldField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public HPgn hpgnNew
        {
            get
            {
                return this.hpgnNewField;
            }
            set
            {
                this.hpgnNewField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string chainId
        {
            get
            {
                return this.chainIdField;
            }
            set
            {
                this.chainIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string sectorId
        {
            get
            {
                return this.sectorIdField;
            }
            set
            {
                this.sectorIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public System.DateTime effectiveDate
        {
            get
            {
                return this.effectiveDateField;
            }
            set
            {
                this.effectiveDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool effectiveDateSpecified
        {
            get
            {
                return this.effectiveDateFieldSpecified;
            }
            set
            {
                this.effectiveDateFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509")]
    public partial class HPgn
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509")]
    public partial class ListedEckIdFailure
    {

        private int indexField;

        private string errorMessageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public int index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509")]
    public partial class ListedEckIdSuccess
    {

        private int indexField;

        private EckId eckIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public int index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public EckId eckId
        {
            get
            {
                return this.eckIdField;
            }
            set
            {
                this.eckIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509")]
    public partial class RetrieveEckIdBatchResponse
    {

        private ListedEckIdSuccess[] successField;

        private ListedEckIdFailure[] failedField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("success", Order = 0)]
        public ListedEckIdSuccess[] success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("failed", Order = 1)]
        public ListedEckIdFailure[] failed
        {
            get
            {
                return this.failedField;
            }
            set
            {
                this.failedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509")]
    public partial class RetrieveEckIdBatchRequest
    {

        private BatchIdentifier batchIdentifierField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public BatchIdentifier batchIdentifier
        {
            get
            {
                return this.batchIdentifierField;
            }
            set
            {
                this.batchIdentifierField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509")]
    public partial class BatchIdentifier
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509")]
    public partial class SubmitEckIdBatchResponse
    {

        private BatchIdentifier batchIdentifierField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public BatchIdentifier batchIdentifier
        {
            get
            {
                return this.batchIdentifierField;
            }
            set
            {
                this.batchIdentifierField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509")]
    public partial class ListedHpgn
    {

        private int indexField;

        private HPgn hPgnField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public int index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public HPgn hPgn
        {
            get
            {
                return this.hPgnField;
            }
            set
            {
                this.hPgnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509")]
    public partial class SubmitEckIdBatchRequest
    {

        private ListedHpgn[] hpgnListField;

        private string chainIdField;

        private string sectorIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("hpgnList", Order = 0)]
        public ListedHpgn[] hpgnList
        {
            get
            {
                return this.hpgnListField;
            }
            set
            {
                this.hpgnListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string chainId
        {
            get
            {
                return this.chainIdField;
            }
            set
            {
                this.chainIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string sectorId
        {
            get
            {
                return this.sectorIdField;
            }
            set
            {
                this.sectorIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509")]
    public partial class RetrieveEckIdResponse
    {

        private EckId eckIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public EckId eckId
        {
            get
            {
                return this.eckIdField;
            }
            set
            {
                this.eckIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509")]
    public partial class RetrieveEckIdRequest
    {

        private HPgn hpgnField;

        private string chainIdField;

        private string sectorIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public HPgn hpgn
        {
            get
            {
                return this.hpgnField;
            }
            set
            {
                this.hpgnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string chainId
        {
            get
            {
                return this.chainIdField;
            }
            set
            {
                this.chainIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string sectorId
        {
            get
            {
                return this.sectorIdField;
            }
            set
            {
                this.sectorIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509")]
    public partial class PingResponse
    {

        private bool availableField;

        private string applicationVersionField;

        private System.DateTime systemTimeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public bool available
        {
            get
            {
                return this.availableField;
            }
            set
            {
                this.availableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string applicationVersion
        {
            get
            {
                return this.applicationVersionField;
            }
            set
            {
                this.applicationVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public System.DateTime systemTime
        {
            get
            {
                return this.systemTimeField;
            }
            set
            {
                this.systemTimeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class pingRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509", Order = 0)]
        public PingRequest pingRequest;

        public pingRequest1()
        {
        }

        public pingRequest1(PingRequest pingRequest)
        {
            this.pingRequest = pingRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class pingResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509", Order = 0)]
        public PingResponse pingResponse;

        public pingResponse1()
        {
        }

        public pingResponse1(PingResponse pingResponse)
        {
            this.pingResponse = pingResponse;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class retrieveEckIdRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509", Order = 0)]
        public RetrieveEckIdRequest retrieveEckIdRequest;

        public retrieveEckIdRequest1()
        {
        }

        public retrieveEckIdRequest1(RetrieveEckIdRequest retrieveEckIdRequest)
        {
            this.retrieveEckIdRequest = retrieveEckIdRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class retrieveEckIdResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509", Order = 0)]
        public RetrieveEckIdResponse retrieveEckIdResponse;

        public retrieveEckIdResponse1()
        {
        }

        public retrieveEckIdResponse1(RetrieveEckIdResponse retrieveEckIdResponse)
        {
            this.retrieveEckIdResponse = retrieveEckIdResponse;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class submitEckIdBatchRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509", Order = 0)]
        public SubmitEckIdBatchRequest submitEckIdBatchRequest;

        public submitEckIdBatchRequest1()
        {
        }

        public submitEckIdBatchRequest1(SubmitEckIdBatchRequest submitEckIdBatchRequest)
        {
            this.submitEckIdBatchRequest = submitEckIdBatchRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class submitEckIdBatchResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509", Order = 0)]
        public SubmitEckIdBatchResponse submitEckIdBatchResponse;

        public submitEckIdBatchResponse1()
        {
        }

        public submitEckIdBatchResponse1(SubmitEckIdBatchResponse submitEckIdBatchResponse)
        {
            this.submitEckIdBatchResponse = submitEckIdBatchResponse;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class retrieveEckIdBatchRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509", Order = 0)]
        public RetrieveEckIdBatchRequest retrieveEckIdBatchRequest;

        public retrieveEckIdBatchRequest1()
        {
        }

        public retrieveEckIdBatchRequest1(RetrieveEckIdBatchRequest retrieveEckIdBatchRequest)
        {
            this.retrieveEckIdBatchRequest = retrieveEckIdBatchRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class retrieveEckIdBatchResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509", Order = 0)]
        public RetrieveEckIdBatchResponse retrieveEckIdBatchResponse;

        public retrieveEckIdBatchResponse1()
        {
        }

        public retrieveEckIdBatchResponse1(RetrieveEckIdBatchResponse retrieveEckIdBatchResponse)
        {
            this.retrieveEckIdBatchResponse = retrieveEckIdBatchResponse;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class replaceEckIdRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509", Order = 0)]
        public ReplaceEckIdRequest replaceEckIdRequest;

        public replaceEckIdRequest1()
        {
        }

        public replaceEckIdRequest1(ReplaceEckIdRequest replaceEckIdRequest)
        {
            this.replaceEckIdRequest = replaceEckIdRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class replaceEckIdResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509", Order = 0)]
        public ReplaceEckIdResponse replaceEckIdResponse;

        public replaceEckIdResponse1()
        {
        }

        public replaceEckIdResponse1(ReplaceEckIdResponse replaceEckIdResponse)
        {
            this.replaceEckIdResponse = replaceEckIdResponse;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class retrieveChainsRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509", Order = 0)]
        public RetrieveChainsRequest retrieveChainsRequest;

        public retrieveChainsRequest1()
        {
        }

        public retrieveChainsRequest1(RetrieveChainsRequest retrieveChainsRequest)
        {
            this.retrieveChainsRequest = retrieveChainsRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class retrieveChainsResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "retrieveChainsResponse", Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509", Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("chain", IsNullable = false)]
        public Chain[] retrieveChainsResponse1;

        public retrieveChainsResponse()
        {
        }

        public retrieveChainsResponse(Chain[] retrieveChainsResponse1)
        {
            this.retrieveChainsResponse1 = retrieveChainsResponse1;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class retrieveSectorsRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509", Order = 0)]
        public RetrieveSectorsRequest retrieveSectorsRequest;

        public retrieveSectorsRequest1()
        {
        }

        public retrieveSectorsRequest1(RetrieveSectorsRequest retrieveSectorsRequest)
        {
            this.retrieveSectorsRequest = retrieveSectorsRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class retrieveSectorsResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "retrieveSectorsResponse", Namespace = "http://xml.eld.nl/schemas/Nummervoorziening/201509", Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("sector", IsNullable = false)]
        public Sector[] retrieveSectorsResponse1;

        public retrieveSectorsResponse()
        {
        }

        public retrieveSectorsResponse(Sector[] retrieveSectorsResponse1)
        {
            this.retrieveSectorsResponse1 = retrieveSectorsResponse1;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NummervoorzieningChannel : INummervoorziening, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NummervoorzieningClient : System.ServiceModel.ClientBase<INummervoorziening>, INummervoorziening
    {

        public NummervoorzieningClient()
        {
        }

        public NummervoorzieningClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public NummervoorzieningClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public NummervoorzieningClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public NummervoorzieningClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public pingResponse1 ping(pingRequest1 request)
        {
            return base.Channel.ping(request);
        }

        public retrieveEckIdResponse1 retrieveEckId(retrieveEckIdRequest1 request)
        {
            return base.Channel.retrieveEckId(request);
        }

        public submitEckIdBatchResponse1 submitEckIdBatch(submitEckIdBatchRequest1 request)
        {
            return base.Channel.submitEckIdBatch(request);
        }

        public retrieveEckIdBatchResponse1 retrieveEckIdBatch(retrieveEckIdBatchRequest1 request)
        {
            return base.Channel.retrieveEckIdBatch(request);
        }

        public replaceEckIdResponse1 replaceEckId(replaceEckIdRequest1 request)
        {
            return base.Channel.replaceEckId(request);
        }

        public retrieveChainsResponse retrieveChains(retrieveChainsRequest1 request)
        {
            return base.Channel.retrieveChains(request);
        }

        public retrieveSectorsResponse retrieveSectors(retrieveSectorsRequest1 request)
        {
            return base.Channel.retrieveSectors(request);
        }
    }
}