//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://id.school/eck/schemas/v1_0", ConfigurationName="SchoolID")]
public interface SchoolID
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://id.school/eck/schemas/v1_0/ping", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    pingResponse1 ping(pingRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://id.school/eck/schemas/v1_0/retrieveStampseudonym", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    retrieveStampseudonymResponse1 retrieveStampseudonym(retrieveStampseudonymRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://id.school/eck/schemas/v1_0/retrieveEckId", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    retrieveEckIdResponse1 retrieveEckId(retrieveEckIdRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://id.school/eck/schemas/v1_0/submitEckIdBatch", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    submitEckIdBatchResponse submitEckIdBatch(submitEckIdBatchRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://id.school/eck/schemas/v1_0/submitStampseudonymBatch", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    submitEckIdBatchResponse submitStampseudonymBatch(submitStampseudonymBatchRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://id.school/eck/schemas/v1_0/retrieveBatch", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    retrieveBatchResponse1 retrieveBatch(retrieveBatchRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://id.school/eck/schemas/v1_0/replaceStampseudonym", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    replaceStampseudonymResponse1 replaceStampseudonym(replaceStampseudonymRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://id.school/eck/schemas/v1_0/retrieveChains", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    retrieveChainsResponse retrieveChains(retrieveChainsRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://id.school/eck/schemas/v1_0/retrieveSectors", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    retrieveSectorsResponse retrieveSectors(retrieveSectorsRequest1 request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.school/eck/schemas/v1_0")]
public partial class PingRequest
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.school/eck/schemas/v1_0")]
public partial class Sector
{
    
    private string idField;
    
    private string nameField;
    
    private string descriptionField;
    
    private System.DateTime lastEditedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public System.DateTime lastEdited
    {
        get
        {
            return this.lastEditedField;
        }
        set
        {
            this.lastEditedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.school/eck/schemas/v1_0")]
public partial class RetrieveSectorsRequest
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.school/eck/schemas/v1_0")]
public partial class Chain
{
    
    private string idField;
    
    private string nameField;
    
    private string descriptionField;
    
    private System.DateTime lastEditedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public System.DateTime lastEdited
    {
        get
        {
            return this.lastEditedField;
        }
        set
        {
            this.lastEditedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.school/eck/schemas/v1_0")]
public partial class RetrieveChainsRequest
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.school/eck/schemas/v1_0")]
public partial class ReplaceStampseudonymResponse
{
    
    private Stampseudonym stampseudonymField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public Stampseudonym stampseudonym
    {
        get
        {
            return this.stampseudonymField;
        }
        set
        {
            this.stampseudonymField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.school/eck/schemas/v1_0")]
public partial class Stampseudonym
{
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.school/eck/schemas/v1_0")]
public partial class ReplaceStampseudonymRequest
{
    
    private HPgn hpgnOldField;
    
    private HPgn hpgnNewField;
    
    private System.DateTime effectiveDateField;
    
    private bool effectiveDateFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public HPgn hpgnOld
    {
        get
        {
            return this.hpgnOldField;
        }
        set
        {
            this.hpgnOldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public HPgn hpgnNew
    {
        get
        {
            return this.hpgnNewField;
        }
        set
        {
            this.hpgnNewField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public System.DateTime effectiveDate
    {
        get
        {
            return this.effectiveDateField;
        }
        set
        {
            this.effectiveDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool effectiveDateSpecified
    {
        get
        {
            return this.effectiveDateFieldSpecified;
        }
        set
        {
            this.effectiveDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.school/eck/schemas/v1_0")]
public partial class HPgn
{
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.school/eck/schemas/v1_0")]
public partial class ListedEntityFailure
{
    
    private int indexField;
    
    private string errorMessageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int index
    {
        get
        {
            return this.indexField;
        }
        set
        {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string errorMessage
    {
        get
        {
            return this.errorMessageField;
        }
        set
        {
            this.errorMessageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.school/eck/schemas/v1_0")]
public partial class ListedEntitySuccess
{
    
    private int indexField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int index
    {
        get
        {
            return this.indexField;
        }
        set
        {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.school/eck/schemas/v1_0")]
public partial class RetrieveBatchResponse
{
    
    private ListedEntitySuccess[] successField;
    
    private ListedEntityFailure[] failedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("success", Order=0)]
    public ListedEntitySuccess[] success
    {
        get
        {
            return this.successField;
        }
        set
        {
            this.successField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("failed", Order=1)]
    public ListedEntityFailure[] failed
    {
        get
        {
            return this.failedField;
        }
        set
        {
            this.failedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.school/eck/schemas/v1_0")]
public partial class RetrieveBatchRequest
{
    
    private BatchIdentifier batchIdentifierField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public BatchIdentifier batchIdentifier
    {
        get
        {
            return this.batchIdentifierField;
        }
        set
        {
            this.batchIdentifierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.school/eck/schemas/v1_0")]
public partial class BatchIdentifier
{
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.school/eck/schemas/v1_0")]
public partial class ListedHpgn
{
    
    private int indexField;
    
    private HPgn hPgnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int index
    {
        get
        {
            return this.indexField;
        }
        set
        {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public HPgn hPgn
    {
        get
        {
            return this.hPgnField;
        }
        set
        {
            this.hPgnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.school/eck/schemas/v1_0")]
public partial class SubmitBatchResponse
{
    
    private BatchIdentifier batchIdentifierField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public BatchIdentifier batchIdentifier
    {
        get
        {
            return this.batchIdentifierField;
        }
        set
        {
            this.batchIdentifierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.school/eck/schemas/v1_0")]
public partial class ListedStampseudonym
{
    
    private int indexField;
    
    private Stampseudonym stampseudonymField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int index
    {
        get
        {
            return this.indexField;
        }
        set
        {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public Stampseudonym stampseudonym
    {
        get
        {
            return this.stampseudonymField;
        }
        set
        {
            this.stampseudonymField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.school/eck/schemas/v1_0")]
public partial class SubmitEckIdBatchRequest
{
    
    private ListedStampseudonym[] stampseudonymListField;
    
    private string chainIdField;
    
    private string sectorIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("stampseudonymList", Order=0)]
    public ListedStampseudonym[] stampseudonymList
    {
        get
        {
            return this.stampseudonymListField;
        }
        set
        {
            this.stampseudonymListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string chainId
    {
        get
        {
            return this.chainIdField;
        }
        set
        {
            this.chainIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string sectorId
    {
        get
        {
            return this.sectorIdField;
        }
        set
        {
            this.sectorIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.school/eck/schemas/v1_0")]
public partial class EckId
{
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.school/eck/schemas/v1_0")]
public partial class RetrieveEckIdResponse
{
    
    private EckId eckIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public EckId eckId
    {
        get
        {
            return this.eckIdField;
        }
        set
        {
            this.eckIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.school/eck/schemas/v1_0")]
public partial class RetrieveEckIdRequest
{
    
    private Stampseudonym stampseudonymField;
    
    private string chainIdField;
    
    private string sectorIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public Stampseudonym stampseudonym
    {
        get
        {
            return this.stampseudonymField;
        }
        set
        {
            this.stampseudonymField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string chainId
    {
        get
        {
            return this.chainIdField;
        }
        set
        {
            this.chainIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string sectorId
    {
        get
        {
            return this.sectorIdField;
        }
        set
        {
            this.sectorIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.school/eck/schemas/v1_0")]
public partial class RetrieveStampseudonymResponse
{
    
    private Stampseudonym stampseudonymField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public Stampseudonym stampseudonym
    {
        get
        {
            return this.stampseudonymField;
        }
        set
        {
            this.stampseudonymField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.school/eck/schemas/v1_0")]
public partial class RetrieveStampseudonymRequest
{
    
    private HPgn hpgnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public HPgn hpgn
    {
        get
        {
            return this.hpgnField;
        }
        set
        {
            this.hpgnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://id.school/eck/schemas/v1_0")]
public partial class PingResponse
{
    
    private bool availableField;
    
    private string applicationVersionField;
    
    private System.DateTime systemTimeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public bool available
    {
        get
        {
            return this.availableField;
        }
        set
        {
            this.availableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string applicationVersion
    {
        get
        {
            return this.applicationVersionField;
        }
        set
        {
            this.applicationVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public System.DateTime systemTime
    {
        get
        {
            return this.systemTimeField;
        }
        set
        {
            this.systemTimeField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class pingRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://id.school/eck/schemas/v1_0", Order=0)]
    public PingRequest pingRequest;
    
    public pingRequest1()
    {
    }
    
    public pingRequest1(PingRequest pingRequest)
    {
        this.pingRequest = pingRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class pingResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://id.school/eck/schemas/v1_0", Order=0)]
    public PingResponse pingResponse;
    
    public pingResponse1()
    {
    }
    
    public pingResponse1(PingResponse pingResponse)
    {
        this.pingResponse = pingResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class retrieveStampseudonymRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://id.school/eck/schemas/v1_0", Order=0)]
    public RetrieveStampseudonymRequest retrieveStampseudonymRequest;
    
    public retrieveStampseudonymRequest1()
    {
    }
    
    public retrieveStampseudonymRequest1(RetrieveStampseudonymRequest retrieveStampseudonymRequest)
    {
        this.retrieveStampseudonymRequest = retrieveStampseudonymRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class retrieveStampseudonymResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://id.school/eck/schemas/v1_0", Order=0)]
    public RetrieveStampseudonymResponse retrieveStampseudonymResponse;
    
    public retrieveStampseudonymResponse1()
    {
    }
    
    public retrieveStampseudonymResponse1(RetrieveStampseudonymResponse retrieveStampseudonymResponse)
    {
        this.retrieveStampseudonymResponse = retrieveStampseudonymResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class retrieveEckIdRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://id.school/eck/schemas/v1_0", Order=0)]
    public RetrieveEckIdRequest retrieveEckIdRequest;
    
    public retrieveEckIdRequest1()
    {
    }
    
    public retrieveEckIdRequest1(RetrieveEckIdRequest retrieveEckIdRequest)
    {
        this.retrieveEckIdRequest = retrieveEckIdRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class retrieveEckIdResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://id.school/eck/schemas/v1_0", Order=0)]
    public RetrieveEckIdResponse retrieveEckIdResponse;
    
    public retrieveEckIdResponse1()
    {
    }
    
    public retrieveEckIdResponse1(RetrieveEckIdResponse retrieveEckIdResponse)
    {
        this.retrieveEckIdResponse = retrieveEckIdResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class submitEckIdBatchRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://id.school/eck/schemas/v1_0", Order=0)]
    public SubmitEckIdBatchRequest submitEckIdBatchRequest;
    
    public submitEckIdBatchRequest1()
    {
    }
    
    public submitEckIdBatchRequest1(SubmitEckIdBatchRequest submitEckIdBatchRequest)
    {
        this.submitEckIdBatchRequest = submitEckIdBatchRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class submitEckIdBatchResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://id.school/eck/schemas/v1_0", Order=0)]
    public SubmitBatchResponse submitBatchResponse;
    
    public submitEckIdBatchResponse()
    {
    }
    
    public submitEckIdBatchResponse(SubmitBatchResponse submitBatchResponse)
    {
        this.submitBatchResponse = submitBatchResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class submitStampseudonymBatchRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="submitStampseudonymBatchRequest", Namespace="http://id.school/eck/schemas/v1_0", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("hpgnList", IsNullable=false)]
    public ListedHpgn[] submitStampseudonymBatchRequest1;
    
    public submitStampseudonymBatchRequest()
    {
    }
    
    public submitStampseudonymBatchRequest(ListedHpgn[] submitStampseudonymBatchRequest1)
    {
        this.submitStampseudonymBatchRequest1 = submitStampseudonymBatchRequest1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class retrieveBatchRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://id.school/eck/schemas/v1_0", Order=0)]
    public RetrieveBatchRequest retrieveBatchRequest;
    
    public retrieveBatchRequest1()
    {
    }
    
    public retrieveBatchRequest1(RetrieveBatchRequest retrieveBatchRequest)
    {
        this.retrieveBatchRequest = retrieveBatchRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class retrieveBatchResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://id.school/eck/schemas/v1_0", Order=0)]
    public RetrieveBatchResponse retrieveBatchResponse;
    
    public retrieveBatchResponse1()
    {
    }
    
    public retrieveBatchResponse1(RetrieveBatchResponse retrieveBatchResponse)
    {
        this.retrieveBatchResponse = retrieveBatchResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class replaceStampseudonymRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://id.school/eck/schemas/v1_0", Order=0)]
    public ReplaceStampseudonymRequest replaceStampseudonymRequest;
    
    public replaceStampseudonymRequest1()
    {
    }
    
    public replaceStampseudonymRequest1(ReplaceStampseudonymRequest replaceStampseudonymRequest)
    {
        this.replaceStampseudonymRequest = replaceStampseudonymRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class replaceStampseudonymResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://id.school/eck/schemas/v1_0", Order=0)]
    public ReplaceStampseudonymResponse replaceStampseudonymResponse;
    
    public replaceStampseudonymResponse1()
    {
    }
    
    public replaceStampseudonymResponse1(ReplaceStampseudonymResponse replaceStampseudonymResponse)
    {
        this.replaceStampseudonymResponse = replaceStampseudonymResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class retrieveChainsRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://id.school/eck/schemas/v1_0", Order=0)]
    public RetrieveChainsRequest retrieveChainsRequest;
    
    public retrieveChainsRequest1()
    {
    }
    
    public retrieveChainsRequest1(RetrieveChainsRequest retrieveChainsRequest)
    {
        this.retrieveChainsRequest = retrieveChainsRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class retrieveChainsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="retrieveChainsResponse", Namespace="http://id.school/eck/schemas/v1_0", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("chain", IsNullable=false)]
    public Chain[] retrieveChainsResponse1;
    
    public retrieveChainsResponse()
    {
    }
    
    public retrieveChainsResponse(Chain[] retrieveChainsResponse1)
    {
        this.retrieveChainsResponse1 = retrieveChainsResponse1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class retrieveSectorsRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://id.school/eck/schemas/v1_0", Order=0)]
    public RetrieveSectorsRequest retrieveSectorsRequest;
    
    public retrieveSectorsRequest1()
    {
    }
    
    public retrieveSectorsRequest1(RetrieveSectorsRequest retrieveSectorsRequest)
    {
        this.retrieveSectorsRequest = retrieveSectorsRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class retrieveSectorsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="retrieveSectorsResponse", Namespace="http://id.school/eck/schemas/v1_0", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("sector", IsNullable=false)]
    public Sector[] retrieveSectorsResponse1;
    
    public retrieveSectorsResponse()
    {
    }
    
    public retrieveSectorsResponse(Sector[] retrieveSectorsResponse1)
    {
        this.retrieveSectorsResponse1 = retrieveSectorsResponse1;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface SchoolIDChannel : SchoolID, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SchoolIDClient : System.ServiceModel.ClientBase<SchoolID>, SchoolID
{
    
    public SchoolIDClient()
    {
    }
    
    public SchoolIDClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SchoolIDClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SchoolIDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SchoolIDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public pingResponse1 ping(pingRequest1 request)
    {
        return base.Channel.ping(request);
    }
    
    public retrieveStampseudonymResponse1 retrieveStampseudonym(retrieveStampseudonymRequest1 request)
    {
        return base.Channel.retrieveStampseudonym(request);
    }
    
    public retrieveEckIdResponse1 retrieveEckId(retrieveEckIdRequest1 request)
    {
        return base.Channel.retrieveEckId(request);
    }
    
    public submitEckIdBatchResponse submitEckIdBatch(submitEckIdBatchRequest1 request)
    {
        return base.Channel.submitEckIdBatch(request);
    }
    
    public submitEckIdBatchResponse submitStampseudonymBatch(submitStampseudonymBatchRequest request)
    {
        return base.Channel.submitStampseudonymBatch(request);
    }
    
    public retrieveBatchResponse1 retrieveBatch(retrieveBatchRequest1 request)
    {
        return base.Channel.retrieveBatch(request);
    }
    
    public replaceStampseudonymResponse1 replaceStampseudonym(replaceStampseudonymRequest1 request)
    {
        return base.Channel.replaceStampseudonym(request);
    }
    
    public retrieveChainsResponse retrieveChains(retrieveChainsRequest1 request)
    {
        return base.Channel.retrieveChains(request);
    }
    
    public retrieveSectorsResponse retrieveSectors(retrieveSectorsRequest1 request)
    {
        return base.Channel.retrieveSectors(request);
    }
}
